version: "3"
services:
  docker-registry:
      image: registry:2
      ports:
        - 5001:5000
      environment:
        - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data
      restart: unless-stopped
      volumes:
        - ./data:/data